### ISSUE TITLE
Trie: v5 Release Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1061]
Follow-up on ethereumjs/merkle-patricia-tree#111 

Release planning for the next major release `v5` (no date yet), please use this to add breaking changes planned for v5 as well as deprecation tasks which should be executed upon.

Note that it might make sense to combine this release with a monorepo transition if planned.

## Breaking Changes

- [ ] Rename from `merkle-patricia-tree` to `@ethereumjs/trie`
- [ ] Reconsider https://github.com/ethereumjs/merkle-patricia-tree/issues/108 (removal of level dependencies or alternative solution) for integration

## Deprecation Tasks

- [ ] Remove deprecated semi-private `_walkTrie()` and `_lookupNode()` methods, see this [comment](https://github.com/ethereumjs/merkle-patricia-tree/pull/135/files/a536e12977f9a079ddf0d1e76965cbb54782fbfc#r535562847) along ethereumjs/merkle-patricia-tree#135
- [ ] Make deprecated `Trie.setRoot()` function private (reverted in `v4.1.0` release from https://github.com/ethereumjs/merkle-patricia-tree/pull/125 with risk of breaking being too high)

**Comment by holgerd77** [comment]
Have consolidated with #1024, will close here.
