### ISSUE TITLE
The Merge: Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1193]
- [EIP Link](https://eips.ethereum.org/EIPS/eip-3675)
- [ETH Magicians discussion thread](https://ethereum-magicians.org/t/eip-3675-upgrade-consensus-to-proof-of-stake/6706/3)
- [Merge Readiness Checklist](https://github.com/ethereum/pm/blob/master/Merge/mainnet-readiness.md)

**Comment by gabrocheleau** [comment]
An EIP draft for The Merge has been published here: https://hackmd.io/@n0ble/upgrade-consensus-to-pos 

Here's a rough list of the tasks for reference:

## Definitions

- `TRANSITION_BLOCK`: The earliest PoS block of the canonical chain, i.e. the PoS block with the lowest block height.

## Block

These changes must be applied from the `TRANSITION_BLOCK` onwards.

###  Block structure

Set the following dynamic block fields to constants:
- [ ] `ommersHash`: `Keccak256(RLP( [] ))`
- [ ] `ommers`: `[]`
- [ ] `difficulty` : `0`
- [ ]  `extraData`: `[]`
- [ ]  `mixHash`: `0x0000000000000000000000000000000000000000000000000000000000000000`
- [ ]  `nonce`: `0x0000000000000000`

[Reference](https://hackmd.io/@n0ble/upgrade-consensus-to-pos#Block-structure) (note that some of these values may change, I've seen ongoing debate on the ETH R&D channel).

### Block validity

- [ ] Remove verification of the block’s `difficulty` value with respect to the difficulty formula.
- [ ] Remove verification of the block’s `nonce` and `mixHash` values with respect to the Ethash function.
- [ ] Remove all validation rules that are evaluated over the list of ommers and each member of this list, except for enforcing this list to be empty.
- [ ] Add verification of the fields noted in block structure as their specified constant value, including the enforcement of empty ommers list.
- [ ] Add verification of block validity with respect to the PoS consensus rules, i.e. assert that there MUST be a corresponding event for the block to consider it valid. Such events are limited to the following:
 
- A `POS_CONSENSUS_VALIDATED` event considering the block or any of its descendants as valid.
-  A `POS_CHAINHEAD_SET` event, including the `POS_BLOCK_FINALIZED` form of this event, designating the block or any of its descendants as the head of the canonical chain.

### Block and Ommer Rewards

Both rewards are deprecated:

- [ ] Remove increasing the balance of the block’s beneficiary account by the basic block reward.
- [ ] Remove increasing the balance of the block’s beneficiary account by the ommer inclusion reward per each ommer.
- [ ] Remove increasing the balance of the ommer’s beneficiary account by the ommer block reward per each ommer.

## Fork choice rule

As of the first `POS_CHAINHEAD_SET`, we move on to the the new PoS LMD-GHOST fork choice rule.

The LMD-GHOST fork-choice rule is described [in this paper in section 3.2](https://arxiv.org/pdf/2003.03052.pdf)

## Network

- [ ] The networking stack SHOULD NOT send the `NewBlockHashes (0x01)` and `NewBlock (0x07)` messages if they advertise the descendant of any terminal PoW block.
- [ ] Beginning with the first POS_BLOCK_FINALIZED event, the networking stack MUST remove the handlers corresponding to the the `NewBlockHashes (0x01)` and `NewBlock (0x07)` messages

**Comment by acolytec3** [comment]
## Testing `The Merge` code options

### Hack the Execution Client
- In order to see the RPC requests from the Consensus client, add the following code block at [this point](https://github.com/ethereumjs/ethereumjs-monorepo/blob/c008e8eb76f520df83eb47c769e3a006bc24124f/packages/client/bin/cli.ts#L171-L171)
```js
  server.on('request', function (req) {
    console.log('Request')
    console.log(req)
  })
```
### Start the Execution Client
- (from monorepo directory root) `cd packages/client`
- `npm run client:start -- --rpc --maxPeers=0`

### Start the Consensus Client (choose your own adventure)

Several of the Consensus clients have branches/forks that support the merge spec to some degree so pick your favorite from below:

#### Nimbus

- Install dependencies following this [guide](https://nimbus.guide/install.html) according to your OS
- Get Nimbus -- `git clone https://github.com/status-im/nimbus-eth2.git`
- `cd nimbus-eth2`
- `git checkout quick-merge-v1` 
- `./scripts/launch_local_testnet.sh --testnet 0 --nodes 4 --disable-htop --stop-at-epoch 8 -- --verify-finalization --discv5:no`
- Go get a cup of coffee.  Nimbus takes a while to build

### Check the logs

Once your consensus client is up and running, you should (eventually) start to see inbound requests using the new `consensus_...` RPC methods that look something like this:
![image](https://user-images.githubusercontent.com/17355484/128203473-a21dacf0-3a38-4e34-bdda-0f147dab31dd.png)

**Comment by holgerd77** [comment]
Closed in favor of #1511
