### ISSUE TITLE
EIP-1559 Readiness Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1257]
This is a tracking issue for the EIP-1559 implementation being done in #1148 and eventual follow-up PRs to make sure all spec changes, open issues and bugs as well as discovered inconsistencies are addressed before a final release.

## TODOs

- [x] `Block`: Decide on `BaseFee` default value #1250 and add implementation
- [x] `Tx`: Update `EIP1559Transaction.toJSON()` method attribute names with final RPC spec naming (link?)
- [x] `Block`: Update `BlockHeader.toJSON()` method attribute names with final RPC spec naming (link?)

## Release

- [x] Add note to access list API being experimental

**Comment by jochem-brouwer** [comment]
[JSON RPC PR](https://github.com/ethereum/eth1.0-specs/pull/47)

**Comment by jochem-brouwer** [comment]
Dumping some stuff I found at the 1559 review (will edit this comment)

BaseTransaction validates r/s max int, 2930 does this also in the constructor.

**Comment by holgerd77** [comment]
Initial release is done - see #1263 - subsequent adoptions or fixes will likely be done in dedicated PRs susequently, will close here.
