### ISSUE TITLE
Tx/Common: Layer 2 Support - Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1288]
As discussed in the latest call the tx library would be a good candidate to get our feet wet with L2/Sidechain/... support. We should check if we can send a tx on the respective L2 network and see if there are adoptions necessary, to the tx library itself or otherwise to the `Common` library (e.g. by adding a specific L2 as a supported network).

This is a tracking issue for the various Layer 2 solutions investigated/added. For a first round I would suggest that we concentrate on L2s being already in production and have some significant amount of traction and/or usage.

## Layer 2 Networks

L2s (or similar networks) we might want to start with:

- [x] [Arbitrum One](https://offchainlabs.com/): Optimistic Rollup, Mainnet Beta, see #1290
- [x] [Polygon PoS Chain](https://polygon.technology/): Ethereum Sidechain, live on Mainnet, #1289 
- [x] [xDai chain](https://www.xdaichain.com/), stable payments blockchain, #1323 

Feel free to add here and open a dedicated issue for the implementation work and discussion along.

**Comment by holgerd77** [comment]
This is now well-documented in the [tx README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx#l2-support) and I don't think we need a tracking issue any more, will close.

For selected additional L2 support we will likely open a dedicated issue for the respective L2 solution.
