### ISSUE TITLE
Client: Merge Interop Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1511]
References

- [EIP-3675](https://eips.ethereum.org/EIPS/eip-3675)
- [Execution Engine API](https://github.com/ethereum/execution-apis/releases/tag/v1.0.0-alpha.2)
- [Merge Sync Writeup](https://github.com/fjl/p2p-drafts/blob/master/merge-sync/merge-sync.md)
- [Test Vectors](https://notes.ethereum.org/@9AeMAlpyQYaAAyuj47BzRw/rkwW3ceVY)
- [mergemock](https://github.com/protolambda/mergemock)

Merge F2F Interop [Setup Instructions](https://hackmd.io/B1nMKhIiRBWRtgP4-d5KHw)

### Milestones

- [x] Common library Merge HF integration #1393
- [x] EIP-3675 Block Format Specification #1393
- [x] EIP-3675 Blockchain TD Handling #1408 
- [x] EIP-3675 HF switch logic in Common #1473 
- [x] EIP-3675 NewBlockHashes, NewBlock behaviour #1493 
- [x] Execution Engine API Input Validation and Method Stubs #1493 
- [x] Client: Web Socket Support #1508 
- [x] Client: Expose Engine API as a separate Server
- [x] Test Vector Setup #1512

**Comment by ryanio** [comment]
Looks like the milestones here were a success being fully completed!

Closing in favor of the successor #1551
