### ISSUE TITLE
Client: Verkle Trie Integration + Proof Consumption - Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1533]
There are recent efforts to replace the current MPT state trie storage datastructure with a new trie format called Verkle Trie which is described in this [draft EIP](https://notes.ethereum.org/@vbuterin/verkle_tree_eip). 

As discussed with @gballet from the go-ethereum team we would like to prototype a verkle trie integration in the EthereumJS client with the main focus on proof consumption and block execution. Guillaume is working on Verkle Trie support for go-ethereum here https://github.com/ethereum/go-ethereum/pull/23630, and outline how a broader network setup might look like is written down [here](https://notes.ethereum.org/@gballet/rJn5JaBSK).

Effort on this is rather broad and this is a tracking issue for high level discussion and TODO checks. Dedicated tasks should rather become it's own place to discuss.

References:

- [Verkle Trie Talk](https://www.youtube.com/watch?v=xJiABLuD06g&t=18351s), Guillaume Ballet, ETHOnline, Oct 15, 2021

Some first TODOs here:

- [ ] `rust-verkle` implementation `WASM` compilation
  - [ ] Analyze if a `WASM` compilation is possible, structural needs, see https://github.com/crate-crypto/rust-verkle/issues/24
  - [ ] Compilation setup and execution from the EthereumJS side
  - [ ] First `VM` `StateManager` experiments and simple tests to do a dedicated Verkle Trie backed state manager (eventually needs some confirmation if this is the correct entry point)
- [ ] Client Proof Consumption: TODO
- [ ] Blockchain, Block, Common: understanding of proof-including block format TODO

**Comment by holgerd77** [comment]
Some more references:

- Fantastic [slides](https://docs.google.com/presentation/d/13bmmLbkKte5QGiJjqpIZLgvKxsYdravIgtytQMPBQ-M/edit#slide=id.g6518b43596c43d74_0) from Dankrad for ACD summary (ACD Call [#401](https://github.com/ethereum/pm/issues/401), Oct 29 2021)
- Also from Dankrad: [Verkle Trie EIP Calculator](https://github.com/ethereum/pm/issues/401)

**Comment by acolytec3** [comment]
[This repo](https://github.com/crate-crypto/rust-verkle-wasm) compiles the verkle verifier to WASM for use in our integration.

**Comment by holgerd77** [comment]
Have now created a base branch [#verkle-stateless-demo ](https://github.com/ethereumjs/ethereumjs-monorepo/tree/verkle-stateless-demo) where we can do the work against and also added some set of branch protection rules along.

For now I've set this to me being the only one allowed to force-push, will make this very carefully and always do a branch backup before. 🙂

**Comment by acolytec3** [comment]
Do we still need this given the other Verkle issues and PR we have? @gabrocheleau @holgerd77
