### ISSUE TITLE
Client: Kintsugi 🍵 Tracking Issue

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1551]
*Kintsugi is the unique and traditional Japanese art of repairing broken, chipped and cracked pottery using lacquer and gold.*

---

### Overview
This issue details the milestones for the Kintsugi 🍵 testnets in November 2021.

Kintsugi Milestones: https://notes.ethereum.org/@djrtwo/kintsugi-milestones
Kintsugi Spec: https://hackmd.io/@n0ble/kintsugi-spec

### Execution Layer

The scope of work on updating EL client software to Kintsugi specification is as follows:

* [x] Implement the new version of EIP-3675
* [x] Implement EIP-4399
* [x] Implement the new version of Engine API server

### [Milestones](https://notes.ethereum.org/rki-W2RvRf-TkVn3ZIvMFA?both#Milestones)

* [x] **M0:** Implementation started
* [x] **M1:** Spec Implemented
* [x] **M2:** 1-to-1 Interop – One EL and one CL team pair off for basic interop testing
* [x] **M3:** Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
* [x] **M5:** All-to-All persistent testnet – All ready EL and CL teams create a long-lived devnet first week of December
* [x] **M6:** Kintsugi🍵 code released – All clients release Kintsugi🍵 code for public consumption

Work-in-progress PR: #1565

**Comment by ryanio** [comment]
this PR is currently at the kintsugi spec v2 changeset, just rebased on master, and will implement the v3 changeset along with updated instructions for joining the latest devnet-3
