### ISSUE TITLE
Client: Kiln🔥🧱 Tracking Issue

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1703]
*Kiln🔥🧱 – the last Merge sprint before launching pre-production testnets. Kiln aims to move client implementations into the production readiness stage.*

*Please note: EthereumJS does not aim to contend as a production mainnet client, but rather participating to ensure compatibility for downstream users of our libraries.*

---

### Overview
This issue details the milestones for the Kiln🔥🧱 testnets starting in February 2022.

Kiln Spec: https://hackmd.io/@n0ble/kiln-spec

### Execution Layer

Changes to Execution layer spec introduced in Kiln:

* [x] Extend semantics of executePayload and forkchoiceUpdated methods [#165](https://github.com/ethereum/execution-apis/pull/165)
* [x] Replace terminal block error with INVALID_TERMINAL_BLOCK status [#170](https://github.com/ethereum/execution-apis/pull/170)
* [x] Refine message ordering. Take 2 [#148](https://github.com/ethereum/execution-apis/pull/148)
* [x] Authentication for engine api [#167](https://github.com/ethereum/execution-apis/pull/167), PR #1723 
  * (pending change to the Engine API and will be added in a subsequent version of the Kiln specification)
* [ ] Add support for [Optimistic Sync](https://github.com/ethereum/consensus-specs/blob/dev/sync/optimistic.md)
  * (for reference, geth's implementation: [beaconsync.go](https://github.com/MariusVanDerWijden/go-ethereum/blob/merge-kiln/eth/downloader/beaconsync.go)) 
#### Milestones

* [x] **M0:** Implementation started
* [x] **M1:** Spec Implemented
* [x] **M2:** 1-to-1 Interop – One EL and one CL team pair off for basic interop testing
* [ ] **M3:** Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
* [ ] **M5:** All-to-All persistent testnet – All ready EL and CL teams create a long-lived devnet
* [ ] **M6:** Kiln🔥🧱 code released – All clients release Kiln🔥🧱 code for public consumption

PRs:
 - v1: #1712
 - v2: #1750
