### ISSUE TITLE
v6 Breaking Release Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1717]
Follow-up on #907
Work branch: [`develop`](https://github.com/ethereumjs/ethereumjs-monorepo/tree/develop)
Replaces #1024 

Update of `develop` branch: no merges / only rebase (~weekly by @holgerd77)
Update of feature branches: no merges / only rebase

**Planned Release Date** (Timeframe): Latest somewhat before Merge HF (~Summer 2022), eventually earlier

#### Error Management

- [ ] Rework of error management with more targeted error messages and error-string-independent handling, work is being done on this by @gabrocheleau in: #1469

#### BigInt Support

- [x] Switch from `BN.js` to native JS BigInts for external API usage and/or inner-functional computations and data handling, so on the entire stack (also switch along API on BN.js using functions (e.g. `Common.nextHardforkBlock()`)).
  - Note: This is highly connected to a decision on #1668 - so an upgrade to `ethereum-cryptography` `v1.0`, since the underlying noble libraries use `BigInt` anyhow which would be an implicit decision to integrate native BigInts throughout the stack.

##### TODOs

- [x] PoC PR on 2. on some selected functions proposing a coherent strategy on how to replace `BNLike`, what values to allow as input and the like, #1744 
- [x] Coherent `ES2020` strategy: `ES2018` + `ES2020.BigInt`, `ES2019.Object`, #1729 

#### Consensus Encapsulation / Separation

- [x] Separate consensus functionality in Blockchain/Block (and eventually other libraries) and give this a unified API. This will allow for an easier consensus switch or replacement. #1044 

#### ESM Support

- [ ] Add ESM Support as outlined in #1654 

#### [ In Discussion / Needs Decision ]

- [x] Make all constructors from libraries with async constructor methods (VM, Blockchain) `protected` #1811
- [ ] Consider a hash/stateRoot genesis handling refactor along Blockchain/VM/Block/Common dependency chain, see https://github.com/ethereumjs/ethereumjs-monorepo/pull/1833#issuecomment-1088445250 and https://github.com/ethereumjs/ethereumjs-monorepo/pull/1833#issuecomment-1091181809 for discussion and TODO summary

#### Standalone StateManager

- [x] Create a standalone `StateManager` package together with a state manager functionality rework (leave all VM related stuff in the VM) and an API overhaul (all interface functions necessary? Genesis functionality?) Issue: #1599 

##### Related TODOs / Decisions

Note: all the TODOs should be re-evaluated in the context of the StateManager rework (still desired to add a certain method? Stuff like that.)

- [x] Re-add `VM: stateManager -> add modifyAccountFields method`, PR #1369 and PR #1763

#### Standalone EVM

- [ ] Extract everything in the `evm` folder as a standalone package and define a stable API. This allows for a cleaner interface towards the EVM and to easier extend the core EVM or to switch out the EVM entirely which will be useful for L2 and other integrations, PR #1862 
  - Related comment: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1705#discussion_r806719750
- [ ] Eventually restructure/sort VM exports (directly expose `Bloom`, other?, unified type location, type/interface exposure, `index.ts` -> `vm.ts`+ `index.ts` only for exports), this needs another look once the EVM extraction is done, also: generally have one alignment look along all the packages (included in the releases)?

#### Other

Below tasks resolved with #1815

- [x] Remove deprecated `state` (Trie) constructor option
- [x] Remove deprecated `generateTxReceipt` function in `runBlock` (preferring newer version located in `runTx`), remove `Receipt` re-exports
- [x] Remove `StateManager.getStateRoot()` `force=true` parameter (also in interface)
- [x] Removed deprecated `EIP2930Receipt` and `EIP1559Receipt` types
- [x] Move `gasRefund` to a tx-level result object instead of `ExecResult` [todo link](https://github.com/ethereumjs/ethereumjs-monorepo/blob/0126581c6e3795d249dfa7522f3cf86e0f0f30b4/packages/vm/src/evm/evm.ts#L191-L193)
- [x] Do `gasUsed` deduplication https://github.com/ethereumjs/ethereumjs-monorepo/issues/1446#issuecomment-1013359621
- [x] Update BaseTxReceipt gasUsed from Buffer to BigInt (suggestion added by @ryanio)
- [x] `runCode` throws if `gasLimit` is `undefined`: the `gasLimit` parameter is mandatory
- [x] Finish #1811 (VM, Blockchain: fix storing unsettled promises) @ryanio

#### TODOs

- [x] Remove deprecated [Blockchain.meta](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/blockchain/src/index.ts#L303) object and `getHead()`/`setHead()` iterator head functions + eventually rename canonical head functions, #1754. PR: #1784
- [x] Limit `Blockchain.iterator()` to return a `number` in function and interface, also `VM.runBlockchain()` and `vmPromise` in client full sync module, #1754

#### [ In Discussion / Needs Decision ]

None.

#### Centralized Default Value Setting

- [x] Switch to centralized default value setting in the main constructor instead of setting in the static constructors, switch to a parameter dict for passing in values to the main constructor (instead of a long list of separate values), make `BlockHeader.fromHeaderData` (would need some check for `Block.fromBlockData`, likely as well) simply an alias for the main constructor instantiation using the same (typed) API, see changes/updates in the tx library for reference #1738 

#### Other TODOs

- [ ] Complete rework of all validation and (format) verification methods, move Block validation methods to Blockchain #1879 
- [x] Remove deprecated `bloom` and `baseFee` parameters and types, #1747
- [ ] Directly throw in validation functions like `BlockHeader.validateGasLimit()`, throw with more appropriate error messages (e.g. EIP-1559 specific), see https://github.com/ethereumjs/ethereumjs-monorepo/pull/1148#issuecomment-834239077, Issue #1889

#### [ In Discussion / Needs Decision ]

None.

### Transaction

- [x] Remove `transactionType` property in favor of `type`, execute on other deprecations, #1739 
- [x] Remove v, r, s aliases for typed txs (`senderR`, `senderS`, `yParity`)
- [ ] Throw when `hash()` is called on unsigned legacy txs (so: align with behavior from typed txs), see also comment added along with #1445, Issue #1890

#### [ In Discussion / Needs Decision ]

None.

### Common

- [x] Set default hardfork to 'london' (Update 2022-01-13 @holgerd77: confirmed), #1657 
- [x] Execute on all deprecation notes (e.g. remove deprecated `Common.forCustomChain()` method), #1633
- [x] Rename method names referring to "active" HFs with the terminology being ambiguous #1674
- [x] Remove `supportedHardforks`, `onlySupported` and `onlyActive` HF [options] #1274
- [x] Make `common.param` return BigInt (since in most cases it is converted)
  - remove redundant conversions, when used as a number do `Number(common.param())`, Issue #1846
- [ ] Introduce more type safety to common `any` responses (chains, hardforks, params) (or otherwise framed: remove remaining `any` usages from `Common`, try to keep low-level though and avoid new data/type structures and rather reuse (or adopt a bit) where possible), Issue #1888 

#### [ In Discussion / Needs Decision ]

  - @ryanio in [this comment](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1632#issuecomment-1012262154): we should keep default exports (helpful pattern), moving to esm exports will help fix these problems for poeple who are having trouble with `"type": "module"` without `esModuleInterop` being true in their tsconfig.

#### Library Renaming

- [ ] Library is still in the old `ethereumjs-util` naming scheme. This should be brought into the new naming scheme and library renamed to `@ethereumjs/util`

#### BigInt Util Functionality/Support

- [x] Library should get an overall analysis on how/where to support the new BigInt integration (BigInt constants, conversion functionality, eventually others).

#### Signing / Hashing Functionality Removal

- [ ] Library should get an analysis if `signature` and `hash` modules should be completely removed and instead [ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography) functionality being used directly, Issues #1845 #1844 
- [ ] Legacy signature functionality using v=27 and v=28 might be able to be encapsulated in the tx library (needs analysis), Issues #1845 #1844 

#### Other TODOs

- [x] Remove deprecated `object` module, Remove deprecated `bnToRlp()` method (`types`) #1809
- [x] Move misplaced `bigIntToHex()` and `bigIntToUnpaddedBuffer()` methods (and tests) from `types` to the `bytes` module, #1825 

#### [ In Discussion / Needs Decision ]

Following TODOs only if no `signature` module removal (see above):

- [ ] Unify return values along https://github.com/ethereumjs/ethereumjs-util/pull/290 for methods like `ecsign` and always return `Buffer`, remove function overloading, merge interfaces like `ECDSASignature` and `ECDSASignatureBuffer` (to: `ECDSASignature`)
- [ ] Check `homesteadOrLater` parameter in `isValidSignature()`
- [ ] Deprecate/remove `fromRpcSig()` function, see doc comment (`toRpcSig()`?)

### Trie

- [x] Replace constructor options with an options dict (like in other libraries), add an options type, #1874
- [ ] Rename from merkle-patricia-tree to @ethereumjs/trie
- [ ] Reconsider https://github.com/ethereumjs/merkle-patricia-tree/issues/108 (removal of level dependencies or alternative solution) for integration
- [x] Remove deprecated semi-private _walkTrie() and _lookupNode() methods, see this comment along
- [ ] Refactor WalkTrie merkle-patricia-tree#135
- [x] Remove deprecated `Trie.setRoot()` function, #1874

**Comment by holgerd77** [comment]
Closed by #2270
