### ISSUE TITLE
EEI/EVM package extraction and refactor tracking issue

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1903]
This issue tracks extracting the EEI and EVM from the VM package and create new packages for those. 

All is open for discussion so is subject to change.

The goal of EEI (Ethereum External Interface) is to provide an implementation of the EEI interface (this interface is located in EVM) to interact with the external environment, such as contract code, storage, account balances, block hashes, etc. 

The goal of the EVM is to provide an interface and implementation to run bytecode. This calls back into the EEI if it needs external information, such as account balances, storages, blockhashes, etc. 

To refactor the current implementation: (Anything with a (?) is stuff I'm not really sure about at this point)

EEI
----

- [x] Remove EVM dependency
- [x] Remove everything related which has to do with gas. (`useGas`, `refundGas`, `subRefund`, `addStipend`, `getGasLeft`). Move this to EVM.
- [x] Remove the `ENV` from `EEI`, this is EVM related and should be moved there. Also remove all getters to this environment (`getCallData`, `getAddress`, etc.)
- [x] Most of the `call` logic (`delegatecall`, `call`, etc.) should also be moved into EVM. Except getting the code for the context of the new message.
- [x] Import `VmState` into EEI and remove it from VM

EVM
----

- [ ] Remove EEI and StateManager dependency
- [ ] Create a minimal EEI interface and export this
- [ ] Import any gas-related logic (touched accounts, warm address, etc.) from EEI into EVM
- [ ] Only dependencies of `EVM` should be `common`, `util` and anything related to precompiles (+ crypto)
- [ ] `runCall` and `runCode` should be moved into one method, the parameters passed on will determine if it is a call or just the code. (Probably the `Message` and this method are the only interface the EVM should provide, together with a constructor which sets the EEI)

I probably missed a few things.

**Comment by jochem-brouwer** [comment]
Small little insight I got today: when we run a Transaction, it essentially has three phases. Bold text is used to signal that this is something which we should (?) not put logic related to this into EVM, but rather into EEI.

Pre-execution phase
----

In this phase, we start preparing the environment to execute code. This is currently encapsuled into `runTx`. What happens here (probably incomplete):

- Update account balance (subtract gas fees and callvalue)
- Update account nonce
- **Read access list and setup this as warmed addresses and warmed storages**
- **Insert account + target into warmed addresses**

Execution phase
---
In this phase we actually run the EVM message. This takes place into `EVM`. We dump the value into the target account, read the code (or in case we don't have a `to` field it is a CREATE message, first generate address then execute the code). In here we start executing the code and run any CALLs to other accounts. Of special interest here is:

- **Selfdestructed accounts**. We need to keep a journal outside of EVM due to the post-execution phase cleanup.
- **Calculating SSTORE/SLOAD gas**. Starting from `Constantinople` we need original storage values (so pre-tx) which should be cached when we first load the slots from disk.

Post-execution cleanup
---
After executing the message: (this is again in `runTx`)

- Refund any gas*gasPrice not spent by the transaction
- Destroy selfdestructed accounts
- Award miner account
- Cleanup touched accounts (`SpuriousDragon` cleanup after Shanghai attacks)



Please note that it is possible to move all this bold logic into EVM. We can do the pre- and post- execution logic into EVM: if we enter a message with depth 0 we should do pre-execution, and if we exit a message with depth 0 we can post-cleanup. We can also add warmed addresses + slots to the environment. But this feels a bit artificial and we already have this logic into EEI, so I think that EEI needs to keep this logic.

**Comment by holgerd77** [comment]
Since EVM/VM refactoring and package extraction have been merged in #1955 and #1974 I will close here.
