### ISSUE TITLE
Monorepo: Build, Compiler and Export Updates

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1946]
We decided that tackling esm support for this breaking change release would be too large of an effort while tooling and dependencies continue to finalize support.

There are a few concepts from #1936 that still have value to bring into this next major release:

- [x] Set [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) and [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports) to `false` (see reasoning [here](https://www.semver-ts.org/#module-interop)) to not force the option for downstream consumers. (this is a breaking change), #1964 

- [x] Activate [declarationMap](https://www.typescriptlang.org/tsconfig#declarationMap) (`declarationMap=true`) as suggested by @MicahZoltu in this comment https://github.com/ethereumjs/ethereumjs-monorepo/pull/1936#discussion_r889802870, #1965

- [x] Remove `dist.browser` builds/folders - not sure if there is any difference in this build anymore since it has a ES2020 target for bigint support now. in maintenance branch we downleveled to ES5 for legacy browser support, which is no longer really needed. downstream consumers can continue to bundle for browsers themselves depending on their specific needs.

- [x] Export all exports from top level. Micah suggested this is better for browser support since browser deep imports still has its challenges. We already do this for many libs like Common, Tx, Block, etc., but it could be done for VM (and blockchain's new genesisStates).

- When doing the actual upgrade to TS esm, we can use Micah's wonderful [typescript-transformer-append-js-extension](https://github.com/Zoltu/typescript-transformer-append-js-extension) to eliminate the need to add .js file extensions to all import paths.

Note from @holgerd77: I will update this post with additional tasks, links, issue references and the like.

**Comment by paulmillr** [comment]
>Set esModuleInterop and allowSyntheticDefaultImports to false (see reasoning [here](https://www.semver-ts.org/#module-interop)) to not force the option for downstream consumers. (this is a breaking change)

Since this is a breaking change, could we do it with this major release? Delaying it will either a) make minor release breaking b) require major release which is 6-12 months away.

I have updated dependencies in ethereum-cryptography to also remove this option.

**Comment by holgerd77** [comment]
> > Set esModuleInterop and allowSyntheticDefaultImports to false (see reasoning [here](https://www.semver-ts.org/#module-interop)) to not force the option for downstream consumers. (this is a breaking change)
> 
> Since this is a breaking change, could we do it with this major release? Delaying it will either a) make minor release breaking b) require major release which is 6-12 months away.
> 
> I have updated dependencies in ethereum-cryptography to also remove this option.

Yeah, just read up a bit on this and it seems very much that we should do, the reason that we otherwise force users into those options is just pretty much compelling.

Yes, then we would/should definitely do along this round of releases.

**Comment by holgerd77** [comment]
Have created an associated issue #1964 for the task execution.

**Comment by sambacha** [comment]
> We decided that tackling esm support for this breaking change release would be too large of an effort while tooling and dependencies continue to finalize support.
> 
> There are a few concepts from #1936 that still have value to bring into this next major release:
> 
> * [x]  Set [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) and [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports) to `false` (see reasoning [here](https://www.semver-ts.org/#module-interop)) to not force the option for downstream consumers. (this is a breaking change), [Monorepo: Remove esModuleInterop and allowSyntheticDefaultImports Options #1964](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1964)
> * [ ]  Activate [declarationMap](https://www.typescriptlang.org/tsconfig#declarationMap) (`declarationMap=true`) as suggested by @MicahZoltu in this comment [develop: esm support #1936 (comment)](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1936#discussion_r889802870), [Monorepo: Activate declarationMap Compiler Option #1965](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1965)
> * [x]  Remove `dist.browser` builds/folders - not sure if there is any difference in this build anymore since it has a ES2020 target for bigint support now. in maintenance branch we downleveled to ES5 for legacy browser support, which is no longer really needed. downstream consumers can continue to bundle for browsers themselves depending on their specific needs.
> * [ ]  Export all exports from top level. Micah suggested this is better for browser support since browser deep imports still has its challenges. We already do this for many libs like Common, Tx, Block, etc., but it could be done for VM (and blockchain's new genesisStates).
> * When doing the actual upgrade to TS esm, we can use Micah's wonderful [typescript-transformer-append-js-extension](https://github.com/Zoltu/typescript-transformer-append-js-extension) to eliminate the need to add .js file extensions to all import paths.
> 
> Note from @holgerd77: I will update this post with additional tasks, links, issue references and the like.

Nice to see esm progress being made! FWIW this conversation was also discussed for the js-ethereum-cryptography library, [see https://github.com/ethereum/js-ethereum-cryptography/pull/40](https://github.com/ethereum/js-ethereum-cryptography/pull/40)


I also created a reference for CJS/ESM issues/"best practices" here [https://github.com/sambacha/typescript-cjs-esm-tests](https://github.com/sambacha/typescript-cjs-esm-tests) you may find it useful. 

One thing to note, you made mention of browser builds, ESM does not support SRI hashes, idk if that is particularly an issue just one of the edge cases. You also shouldn't need to prefix your imports with`.js`, though that depends really how you plan on providing your compiled output. 

also, providing a `dist` folder is useful in that end users don't have to compile it to get it, it can be published on github packages as an example (npm can be pure source).

Thanks for all yalls work, looking forward to the day EWASM is a reality so javascript can be the most performant language on the EVM :))))))

**Comment by holgerd77** [comment]
There might still be selected single items to be done here especially regarding the exports (so: discover a single property/function/constant which might be useful to export from the top level), but this is rather falling under clean-up (in the sense of: before final releases though).

Structurally this issue is done though. Will close.
