### ISSUE TITLE
Master tracker for snap sync

### ISSUE THREAD

**Issue by g11tech** [ethereumjs/ethereumjs-monorepo#2100]
This is a master tracker for snap-sync PR/tasks

- [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/1883
  - [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/1893
- [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/1731
- [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/1897
  - [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/1933
  - [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/2119
- [x] Test call and verify other methods
  - [x] Test Call GetAccountRange: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2157
  - [x] Test Call GetByteCodes: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2157
  - [x] Test Call GetTrieNodes: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2282
- [ ] Build fetchers and just dump it into a mock MPT 
  - [x] GetAccountRange
      - [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/2070
      - [x] https://github.com/ethereumjs/ethereumjs-monorepo/pull/2107
  - [x] GetStorageRange: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2345
  - [x] GetByteCodes: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2602
  - [ ] GetTrieNodes: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2623
- [ ] Build MPT and successfully run move the chain forward on a normal eth sync
- [ ] Chart out behavior of non static peer and map next steps

cc @scorbajio @jochem-brouwer @holgerd77 @acolytec3

**Comment by scorbajio** [comment]
#1897 is being continued at #2107.

**Comment by scorbajio** [comment]
Closing this and continuing on #2874.

**Comment by scorbajio** [comment]
Closing this and continuing on https://github.com/ethereumjs/ethereumjs-monorepo/issues/2874.
