### ISSUE TITLE
Tiny Fixes Meta Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2105]
Will reopen this issue in favor of #905 to give this more visibility again since this has proven to be very handy.

To recap: this issue is for collecting small tasks which are too tiny to address on its own. Instead they can be done along other PRs, also possible to go into this list and work down tasks in batch from time to time.

So feel free to directly edit this initial post and add, check or remove. 🙂 

## StateManager

- ~See if `eslint-disable-next-line implicit-dependencies/no-implicit` for `js-sdsl` depdendency import from [PR #2285](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2285/files#diff-27995baca2e3cab4168cca2adf0592d1ef14e2feb853cd540972551098c8f612) can be removed (should be possible)~

## EVM

- [ ] Investigate if EVM-step-event stop issue from #2290 could need additional code docs along the `step` event docs

## Common

- [ ] Mark `shanghai` HF as experimental/not-finished as mentioned in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2459/files#r1059136654

## Util

- [ ] Document new `intToBuffer()` method in `bytes` module, see https://github.com/ethereumjs/ethereumjs-monorepo/pull/2409/files#diff-82756c063b1cbe4840166da5b6381648c96064b1867c3ce972196581fd0b4b66

**Comment by gabrocheleau** [comment]
I guess this can be closed?

**Comment by holgerd77** [comment]
> I guess this can be closed?

No, this is a permanent issue to track tiny issues which are not worth to be dealt with on its own. Just add to the initial comment if you have something.
