### ISSUE TITLE
To-do list from Shandong test net

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2362]
This is a tracker issue for items we've uncovered during the course of the Shandong test net:

### JSON-RPC items
- [x] Fix remaining `eth_estimateGas` bugs - reference 8791e70f07906d082fb8e9bc8853668f41526d30 for proposed fixes - #2411 
  - [x] Update `RpcTx` interface to include EIP1559 gas fiels
  - [x] Decide if we should provide default values if no gas related fields are included (e.g. `gasPrice` or `maxFeePerGas`)
  - [x] Default `block` parameter to `latest` if not passed in RPC call parameters
  - [x] Add `block` to `txData` parameter passed to `TransactionFactory` call
- [ ] Add `eth_feeHistory` RPC endpoint - reference fb4e8878361aaa1bd52da618b5429fefeb6ed64d for ideas on how to properly implement this -- this is necessary if we want the [standard faucet](https://github.com/komputing/FaucETH/) used for testnets to work since it depends on `eth_feeHistory`
- [x] Add `eth_gasPrice` RPC endpoint - this is a critical one for Metamask to work right with our client.  My Shandong implementation is very naive and seems to completely underestimate gas prices.  Reference 5d7301e75fdc7a2eaeeb76d6a91cec3970c36c5f and 20c1324705a8c0f13032c438ec7cee0ead0fe288 for ideas on how to get started with this one - #2396 in flight
- [x] Add `txpool_content` RPC endpoint - this is a Geth endpoint used by Blockscout to retrieve pending transactions to display in the Block Explorer - See f5d68c7dbe31446bf305b503e7c02af485d5e64a and 63ee9116b0c19b6e46528471bceb221af856d611 for code - #2410 
- [x] Update `eth_call` validation error messages to provide better clarity - See fa7fd59e6bb252ae0a7c3b9bc2d9c6eb24aaaebc, b4c0505cc85bc7c6011b911fe08a5ab61f0b0c67, c6098699ce7639c376f68ec2d0a04ecb74f83a5b #2411 
- [x] Add `debug_traceTransaction` to allow blockscout to display internal transactions - first draft here - c9e128bfae6ce96bbe580557225cbe0d45ef7818

Add### Transaction Pool logic
- [x] Fix txPool validation logic bug - In the `TxPool.validate` method, new transactions are currently validated against whatever state pulled from whatever state root the client's State manager currently happens to be set at and not necessarily the current block height so pending transactions are often dropped if the state root is set to genesis or some other ancient block and the tx sender didn't have a correct balance then.  Reference 1c46aa3eb5c392b9953fa0e571d542625032dc95 and 58cdd33c67bca72712144063ce04a99d7a955578 and 9c810411aa52b9d63d835aad00a056bf64016cd6 for the appropriate solution and corresponding test fixes - #2382 
- [x] Research pending tx gossip issues between EthJS nodes.  It appears that txns aren't being cleanly gossiped around the testnet
  - [x] Fix encoding/decoding for `Transactions` and `NewPooledTransactionHashes` devp2p message handlers -- see 0937ca24882f5646982d5ab4dc6cf90d2c0ca314 and 85938b96f866f016fe7c4c3658162d2466b0f7a9 #2382

**Comment by holgerd77** [comment]
Short note on the `RpcTx` interface from client: we should delete this altogether and instead use the [JsonRpcTx](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/types.ts#L270) interface from the tx library and make this the "official" item to use (or am I missing something around the use case here since `RpcTx` is so strangely underspecified? 🤔).

Along we should also add a `TransactionFactory.fromRPC()` static constructor for the tx library using `JsonRpcTx` for typing, realised that this is still missing when reviewing #2315 and seeing that there is such a method for block but not tx yet, which is somewhat inconsistent (this way with the `normalize*` method is *okayish*, but still not so optimal from a UX perspective).

**Comment by acolytec3** [comment]
> Short note on the `RpcTx` interface from client: we should delete this altogether and instead use the [JsonRpcTx](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/types.ts#L270) interface from the tx library and make this the "official" item to use (or am I missing something around the use case here since `RpcTx` is so strangely underspecified? thinking).
> 

I think you're right about `RpcTx`.  Not sure what's going on there but will update it in my next commits for Shandong.  Going to try and get `eth_call` working correctly.

**Comment by holgerd77** [comment]
I think this can be closed with `debug_traceTransaction` being implemented in #2444. Will do, feel free to reopen if I have missed something.

**Comment by holgerd77** [comment]
Ah, will re-open, `feeHistory` hasn't been tackled after the first draft implementation from #2413, right?

**Comment by acolytec3** [comment]
> Ah, will re-open, `feeHistory` hasn't been tackled after the first draft implementation from #2413, right?

Ah, you're right.

**Comment by holgerd77** [comment]
feeHistory RPC method has a dedicated own issue in #2413 and all other items are checked, will close here.
