### ISSUE TITLE
v7 Breaking Release Planning (old)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2428]
Follow-up on #1717 

Next breaking release round for the monorepo libraries, intended timeline (all 2023):

- `March/April`: create `v7-develop` branch (version name important!), active development start
- `May/June`: First round of `Beta` releases
- `July` or `September/October`: Final Releases

### Monorepo

- [ ] Monorepo-wide `Buffer` removal (Browser & create-react-app compatibility), @acolytec3, everyone
- [ ] Switch to ESM (building upon #1632), @acolytec3, other

### VM/EVM

- [ ] Remove touched accounts in EEI, @jochem-brouwer
- [ ] Remove warm addresses in EEI, @jochem-brouwer 

### Transaction

- [ ] Refactoring replacing inheritance with modular typed-txs-fitting structure

### Common

- [ ] Rename `Merge` HF to `Paris`, #2360 

### Block

- [ ] Consistently use `receiptsRoot` and `transactionsRoot` instead of `receiptsTrie` and `transactionsTrie` (To be considered, see [discussion](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2259#discussion_r1061087405))

**Comment by holgerd77** [comment]
Recreated this issue here #2561 for greater visibility, will close here.
