### ISSUE TITLE
EOF EIPs tracking issue

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2454]
Related PRs;

- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2453
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2446

Problems:

- [ ] EOF explicitly changes the behavior of contracts when compared to "legacy" contracts. Update EVM to reflect this internally (so we produce correct `step` events (e.g. `RJUMP` on a legacy contract should report `INVALID` and not `RJUMP` in the event). Also, some of the EOF properties allows us to optimize some things, such as EIP5450 ensures that no stack underflow can happen.
- [ ] Likely overhaul EVM such that legacy contracts are treated as EOF0 contracts
- [ ] Refactor EVM such that we have multiple EVM engines (now we have very ugly checks to see if we can use, for instance, RJUMP - is 3540/4200 activated? And are we on an EOF contract? Then the opcode is defined, but else we are on legacy and it is undefined). It would also be nice to have engines like IstanbulEVM, BerlinEVM, etc. (This also fixes the problem with clashing opcodes like EIP2315 / 4200)

**Comment by jochem-brouwer** [comment]
EOF got merged in https://github.com/ethereumjs/ethereumjs-monorepo/pull/3440
