### ISSUE TITLE
4844 Todo List

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2542]
- [ ] Disallow 0 blob Type 5 transactions in mempool and at protocol
- [ ] Update KZG library usage to do only single proof validation and not aggregate proof validation
- [ ] Integrate RustKZG WASM build and add browser tests

**Comment by paulmillr** [comment]
wasm is not supported in all environments, for example, in metamask. There is also a CSP which prohibits wasm.

At some point it would be optimal to have pure js KZG library.

**Comment by acolytec3** [comment]
> wasm is not supported in all environments, for example, in metamask. There is also a CSP which prohibits wasm.
> 
> At some point it would be optimal to have pure js KZG library.

I believe there is one in the works. Let me check with Kev on the status of it.
