### ISSUE TITLE
v7 Breaking Release Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2561]
Follow-up on #1717 

Next breaking release round for the monorepo libraries, intended timeline (all 2023):

- `March/April`: create `v7-develop` branch (version name important!), active development start
- `May/June`: First round of `Beta` releases
- `July` or `September/October`: Final Releases

### Monorepo

- [ ] Monorepo-wide `Buffer` removal (Browser & create-react-app compatibility), @acolytec3, everyone
- [ ] Switch to ESM (building upon #1632), @acolytec3, other

### VM/EVM

- [ ] Remove touched accounts in EEI, @jochem-brouwer
- [ ] Remove warm addresses in EEI, @jochem-brouwer 

### Transaction

- [ ] Refactoring replacing inheritance with modular typed-txs-fitting structure

### Common

- [ ] Rename `Merge` HF to `Paris`, #2360 

### Block

- [ ] Consistently use `receiptsRoot` and `transactionsRoot` instead of `receiptsTrie` and `transactionsTrie` (To be considered, see [discussion](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2259#discussion_r1061087405))

**Comment by jochem-brouwer** [comment]
I was planning to ship https://github.com/ethereumjs/ethereumjs-monorepo/pull/2000 this month, but it would make sense if we remove the warm/touched addresses/accounts in EEI first, so will start with that.

**Comment by acolytec3** [comment]
> I was planning to ship #2000 this month, but it would make sense if we remove the warm/touched addresses/accounts in EEI first, so will start with that.

No strong opinion about warmed/touched accounts but that minimal EEI would be a big win for devs.  It still takes a fair bit of boilerplate to get a standalone EVM instantiated (unintuitively requires you to import the `VM` so you can get the `EEI`.

**Comment by jochem-brouwer** [comment]
My EVM/VM points regarding the touched/warm accounts is in #2604

**Comment by Bezzo100-lab** [comment]
Help

**Comment by holgerd77** [comment]
Closed by #2945
