### ISSUE TITLE
`@ethereumjs/wallet` integration TODO list

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2731]
- [x] initial integration of `wallet` into monorepo - #2729 
- [x] Replace all `buffer` references with `Uint8Array` #2739 
- [x] Integrate tests into CI #2738 
- [x] Update `ethereum-cryptography` dep to v2.0.0 #2737 
- [x] Clean up docs - #2732 
- [x] Update `ethers` devDependency to v6 - #2747
- [x] Ensure linter/prettier works correctly with `wallet`- partly finished by #2739 
  -Review the `eslint` rules I disabled in #2739 to see if they can be switched back on
- [x] Switch from `mocha` to `tape` in tests #2742 
- [ ] Remove conflicting types/node devdependency

**Comment by Coollaitar** [comment]
Updated dependencies of ethereum-cryptography to v2.0.0 #2734 

- [x] Update ethereum-cryptography dep to v2.0.0

**Comment by Coollaitar** [comment]
Can you please elaborate in which files `buffer` should be replaced with `Uint8Array`?

**Comment by acolytec3** [comment]
> Can you please elaborate in which files `buffer` should be replaced with `Uint8Array`?

Anywhere `buffers ` are used in this new package, they need to be placed with `Uint8Arrays`.

**Comment by Coollaitar** [comment]
> > Can you please elaborate in which files `buffer` should be replaced with `Uint8Array`?
> 
> Anywhere `buffers ` are used in this new package, they need to be placed with `Uint8Arrays`.

Okay, I will make a PR for that.

**Comment by Coollaitar** [comment]
Updated dependencies of `ethereum-cryptography` to v2.0.0 https://github.com/ethereumjs/ethereumjs-monorepo/pull/2737

- [x] Update ethereum-cryptography dep to v2.0.0

**Comment by gabrocheleau** [comment]
Can this be closed @acolytec3 ? Seems like all todos have been completed.

**Comment by acolytec3** [comment]
We should also clean up the conflicting `types/node` devDependency. I don't think there's any actual work other than removing the ones from `wallet` but we should do this so we don't have duplicate conflicting dependencies in our repo.

**Comment by gabrocheleau** [comment]
> We should also clean up the conflicting `types/node` devDependency. I don't think there's any actual work other than removing the ones from `wallet` but we should do this so we don't have duplicate conflicting dependencies in our repo.

So just this: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2793 ?

**Comment by acolytec3** [comment]
> > We should also clean up the conflicting `types/node` devDependency. I don't think there's any actual work other than removing the ones from `wallet` but we should do this so we don't have duplicate conflicting dependencies in our repo.
> 
> So just this: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2793 ? 

Yessir. I meant to submit this since I had done it locally. Will approve once CI passes.
