### ISSUE TITLE
Make the browser client great(er) again: TO-DO list

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2777]
Following on the work done in #2758 to excise the `libp2p` transport layer for `devp2p`, this tracking issue replaces #1967 based on a reimagining of what a browser implementation of the client will do.  Below is a list of items needed to push this work forward + some ideas on where this will go

## Concrete TODOs
- [ ] - Figure out the best way to remove the replacement in `[monorepo-root]/packages/client/browser/util` and just use the existing code in `src/util/index.ts`
- [ ] - Resolve conflicting `@types/node` dependencies between `ethers` and `client`, which will allow for potential use of the `ethersStateManager` in future iterations of the client

## Big ideas
- [ ] - Explore integrating the Lodestar browser light client with our browser client via some variant of engine API calls (maybe using `jayson` browser RPC stuff)
- [ ] - Explore integration of Ultralight with browser client for retrieving block data
