### ISSUE TITLE
`vitest` and ESM todos

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2788]
After merging the big PR with vitest and ESM path extensions, we have a few todos left

- [ ] Rewrite the Ethereum -Tests runner to use ESM and run in vitest
- [x] Replace tape with vitest in client
- [ ] Get browser tests working for all packages

**Comment by holgerd77** [comment]
Very small issue and we will never re-find this anyhow and some stuff addressed.

Will close.
