### ISSUE TITLE
To-do list from #3735

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3750]
I tackled a number of additional items in this PR that I'd like to add to the master branch though this PR is no longer viable.

- [x] - Add types for `common` and `devp2p` events
- [x] - Rewrite devp2p `eth-simulator` tests to make sense
~~- [ ] - Remove LES tests from both devp2p and client~~
- [x] - Rewrite `test/integration/miner.spec.ts` in `client` to use `inlineClient` (and related changes) will be closed by #3757

**Comment by acolytec3** [comment]
Missing accomplished
