### ISSUE TITLE
Codecov troubleshooting tracker

### ISSUE THREAD

**Issue by scorbajio** [ethereumjs/ethereumjs-monorepo#3754]
- [ ] The master branch isn't having coverage pushed/calculated/visualized, so I'll see if this is just a misconfig or something
- [ ] Some packages (devp2p, wallet, genesis, client) aren't having their coverage files uploaded? Or, atleast they're not showing up on codecov at the moment, so I'll triage and followup here.
- [ ] As mentions by @jochem-brouwer, most of the coverage diffs seem to not be calculates/reported (https://github.com/ethereumjs/ethereumjs-monorepo/pull/3376#issuecomment-2406199634).
- [ ] `rlp` and `ethash` packages are uploading coverage reports, but their reports are erroring out as unusable. I remember working on this before and opening a codecov ticket on it too (in the codecov official repo) that didn't get much activity, but will look into and followup on this on as well.
