### ISSUE TITLE
Berlin Hardfork Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#736]
There are now the first EIPs being [accepted for the Berlin HF](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2084.md#decisions-made), so we can (and should) relatively imminently start working on the integration, since planned [timeline](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2084.md#decisions-made) is relatively dense (June: Testnets, End of June (personal estimate: won't happen, but anyhow 😄): mainnet).

This is a meta issue to help on overall planning and coordination.

## Suggested Procedure

I would suggest to directly work towards `master` and release implemented features early on as `experimental` to get things out early and allow people to play around. First EIP-PR (or alternatively a separate preparatory PR) needs to update the [common](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/common) library and in a first round add some boilerplate for `berlin` to have the HF keyword ready and allow for a clean HF switch in the other libraries.

## Entry Points

- [EIP-2070 Berlin HF Meta EIP](https://github.com/ethereum/EIPs/blob/54ad2316165afe272f92dc198cc80d26d349cd0b/EIPS/eip-2070.md) (canonical source)
- [eth.wiki Berlin Roadmap](https://eth.wiki/en/roadmap/berlin)
- [GitHub ethereum/pm "Berlin" search](https://github.com/ethereum/pm/search?q=Berlin&unscoped_q=Berlin)
- [ACD 84, Decisions on EIP-2537, EIP-2315](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2084.md#decisions-made)

### General

- [x] Preparatory `berlin` boilerplate update on the [common](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/common) library similar to https://github.com/ethereumjs/ethereumjs-common/pull/51 to allow for clean HF switch

### EIPs

- [x] [EIP-2315](https://eips.ethereum.org/EIPS/eip-2315) Simple Subroutines for the EVM, Issue https://github.com/ethereumjs/ethereumjs-vm/issues/737
- [x] [EIP-2537](https://github.com/ethereum/EIPs/pull/2537) BLS12-381 Curve Operation Precompiles, Issue https://github.com/ethereumjs/ethereumjs-vm/issues/738

### Testing

- [x] Update [ethereumjs-testing](https://github.com/ethereumjs/ethereumjs-testing) to a latest (currently still pre-Berlin) state of the official [ethereum/tests](https://github.com/ethereum/tests) and integrate on the VM, see https://github.com/ethereumjs/ethereumjs-testing/issues/44
- [ ] Further [ethereumjs-testing](https://github.com/ethereumjs/ethereumjs-testing) upgrades and integration once `berlin` tests get merged
- [ ] Follow discussion on test improvements (see e.g. [ACD 84 section](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2084.md#4-testing-updates), eventually join planned test call

Following `Istanbul` HF Planning: #501

**Comment by holgerd77** [comment]
Taking over from a chat comment from @jochem-brouwer:

>https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%20101.md#1d-final-gono-go-for-berlin-eips
>
>EIPs which seem to be confirmed for Berlin are 2565, 2315, 2929, 2930, and 2718
>
>We'd need 2565, 2930, 2718

Comment would need to be integrated in the issue TODO list

**Comment by holgerd77** [comment]
Closed by #1151
