### ISSUE TITLE
Tiny Fixes Meta Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#905]
This is a meta issue to collect small fixes not worth a dedicated PR. Please collect in the TODO list below and check or delete from the TODO list once a PR is up (so not only when it is merged but on push):

#### common

- [ ] Minimum HF for EIP-3198 (BASEFEE opcode) is still set to `london` and it is therefore not possible to run in isolation. This should be switched to `berlin` and instead 1559 added as a required EIP (with `"requiredEIPs": [1559]`). This will allow to instantiate with `berlin` and then just `1559` and `3198` being activated
- [ ] Rename `tests/customChains.ts` -> `tests/customChains.spec.ts` for being included in the test runner
- [ ] Expose `_calcNextForkHash()` method (-> `calcNextForkHash()`, include in API docs)

#### devp2p

- [x] Update `devp2p` [README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/devp2p) header, remove very old `node-devp2p` package references (directly in first section)

#### client

- [ ] Add suggestion from https://github.com/ethereumjs/ethereumjs-monorepo/pull/1428#discussion_r697614565
- [ ] Add suggestion from https://github.com/ethereumjs/ethereumjs-monorepo/pull/1538/files#r734001330

#### tx

- [x] Inline default `baseFee` value in `getUpfrontCost` ([link](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1148#discussion_r637437606)) (added [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1272/files#r641885256))
- [ ] Add note to access list API being experimental, see #1267 
- [ ] 2930 uses yParity, 1559 uses v (from @jochem-brouwer, not sure about the context, needs look into the code base)
- [ ] Update all internal monorepo references from deprecated `tx.transactionType` to `tx.type`

#### block

- [x] Block import package name is wrong in the v3.3.0 [release note](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblock%403.3.0) example: update from `ethereumjs-block` to `@ethereumjs/block`
  - [x] also add `import { BN } from 'ethereumjs-util'` for complete example
  - [x] add example with `calcNextBaseFee()` to block README.

#### VM

- [x] VM v5.4.0 [release notes](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.4.0): `VM.runBlocks()` -> `VM.runBlock()`
- [x] uppercase `vm/developer.md` to DEVELOPER.md to match our other internal docs files and update the link to it from vm/README.md
- [ ] Add benchmark URL to README https://ethereumjs.github.io/ethereumjs-monorepo/dev/bench/vm/

#### Trie

- [x] Add https://github.com/ethereumjs/ethereumjs-monorepo/pull/1301 to the `v4.2.1` CHANGELOG entry
- [ ] Add benchmark URL to README https://ethereumjs.github.io/ethereumjs-monorepo/dev/bench/trie/

**Comment by jochem-brouwer** [comment]
Linking #923 

NPM docs also seem to be outdated - default hardfork is now `Istanbul`.

**Comment by holgerd77** [comment]
@jochem-brouwer can you directly collect in the TODO list from the initial post? I think this is otherwise getting out of hand and hard to keep track (you should be able to modify my post, or aren't you?)?

**Comment by jochem-brouwer** [comment]
Yep, will do, also in the future 👍

**Comment by holgerd77** [comment]
Various issues open here, short reminder to pick these up along future PRs.

**Comment by holgerd77** [comment]
Have cleared out the issue list (all completed) and started on a new round by adding a new item here (don't think it's worth it to keep this for historical reference in this context here).

**Comment by holgerd77** [comment]
The list above is likely out of date and needs some validation and update.

**Comment by holgerd77** [comment]
Will close here, most of the issues left are outdated, so won't give this further attention.

Instead I will open a new similar issue to give this more visibility again.
